project:
  type: website

website:
  title: "E155 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Proposal
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



